import type { BlockDefinition } from '@/types/blocks';

export const BLOCK_REGISTRY: BlockDefinition[] = [
  {
    type: 'chat',
    label: 'Chat',
    description: 'Interactive chat panel with streaming support',
    icon: 'MessageSquare',
    defaultW: 6, defaultH: 4,
    defaultProps: { showTimestamps: true, showAvatars: true },
    requiredCapabilities: ['chat', 'streaming'],
    frontend: 'copilotkit',
  },
  {
    type: 'results',
    label: 'Results',
    description: 'Displays structured agent results: cards, JSON, text',
    icon: 'LayoutList',
    defaultW: 6, defaultH: 3,
    defaultProps: { format: 'auto' },
    requiredCapabilities: ['structuredOutput'],
    frontend: 'copilotkit',
  },
  {
    type: 'toolActivity',
    label: 'Tool Activity',
    description: 'Live feed of tool calls and their results',
    icon: 'Wrench',
    defaultW: 4, defaultH: 3,
    defaultProps: { showArgs: true, showResults: true },
    requiredCapabilities: ['toolCalls', 'toolResults'],
    frontend: 'copilotkit',
  },
  {
    type: 'approvals',
    label: 'Approvals',
    description: 'Human-in-the-loop approval requests',
    icon: 'ShieldCheck',
    defaultW: 4, defaultH: 2,
    defaultProps: {},
    requiredCapabilities: ['approvals'],
    frontend: 'copilotkit',
  },
  {
    type: 'logs',
    label: 'Logs',
    description: 'Execution logs, errors, and debug output',
    icon: 'ScrollText',
    defaultW: 12, defaultH: 2,
    defaultProps: { level: 'info', autoScroll: true },
    requiredCapabilities: ['logs'],
    frontend: 'copilotkit',
  },
  {
    type: 'status',
    label: 'Status',
    description: 'Agent status, progress bar, and state indicator',
    icon: 'Activity',
    defaultW: 3, defaultH: 1,
    defaultProps: {},
    requiredCapabilities: ['progress'],
    frontend: 'copilotkit',
  },
  {
    type: 'form',
    label: 'Form',
    description: 'Dynamic input form for agent parameters',
    icon: 'FileInput',
    defaultW: 4, defaultH: 3,
    defaultProps: { fields: [] },
    requiredCapabilities: [],
    frontend: 'copilotkit',
  },
  {
    type: 'table',
    label: 'Table',
    description: 'Data table with sorting and filtering',
    icon: 'Table',
    defaultW: 6, defaultH: 3,
    defaultProps: { columns: [], pagination: true },
    requiredCapabilities: ['structuredOutput'],
    frontend: 'copilotkit',
  },
  {
    type: 'chart',
    label: 'Chart',
    description: 'Visualize data as bar, line, or pie charts',
    icon: 'BarChart3',
    defaultW: 6, defaultH: 3,
    defaultProps: { chartType: 'bar' },
    requiredCapabilities: ['structuredOutput'],
    frontend: 'copilotkit',
  },
  {
    type: 'dashboard',
    label: 'Dashboard',
    description: 'Composite panel with KPI cards and metrics',
    icon: 'LayoutDashboard',
    defaultW: 12, defaultH: 2,
    defaultProps: { metrics: [] },
    requiredCapabilities: ['structuredOutput'],
    frontend: 'copilotkit',
  },
  {
    type: 'cards',
    label: 'Cards',
    description: 'Card grid for structured items',
    icon: 'Layers',
    defaultW: 6, defaultH: 3,
    defaultProps: {},
    requiredCapabilities: ['structuredOutput'],
    frontend: 'copilotkit',
  },
  {
    type: 'panel',
    label: 'Panel',
    description: 'Generic container panel with title',
    icon: 'PanelTop',
    defaultW: 6, defaultH: 2,
    defaultProps: { title: 'Panel' },
    requiredCapabilities: [],
    frontend: 'copilotkit',
  },
  {
    type: 'markdown',
    label: 'Markdown',
    description: 'Render markdown content from agent',
    icon: 'FileText',
    defaultW: 6, defaultH: 3,
    defaultProps: { content: '' },
    requiredCapabilities: [],
    frontend: 'copilotkit',
  },
  // ─── LangSmith-specific blocks ───
  {
    type: 'traceViewer',
    label: 'Trace Viewer',
    description: 'LangSmith trace timeline showing agent execution steps',
    icon: 'GitBranch',
    defaultW: 12, defaultH: 4,
    defaultProps: { showLatency: true, showTokens: true, expandByDefault: false },
    requiredCapabilities: ['logs', 'toolCalls'],
    frontend: 'copilotkit',
  },
  {
    type: 'feedback',
    label: 'Feedback',
    description: 'LangSmith feedback collector for agent responses',
    icon: 'ThumbsUp',
    defaultW: 4, defaultH: 2,
    defaultProps: { feedbackType: 'thumbs', allowComment: true },
    requiredCapabilities: [],
    frontend: 'copilotkit',
  },
  {
    type: 'dataset',
    label: 'Dataset',
    description: 'LangSmith dataset browser and example viewer',
    icon: 'Database',
    defaultW: 6, defaultH: 3,
    defaultProps: { showExamples: true, maxRows: 50 },
    requiredCapabilities: ['structuredOutput'],
    frontend: 'copilotkit',
  },
  {
    type: 'annotationQueue',
    label: 'Annotation Queue',
    description: 'LangSmith annotation queue for human review workflows',
    icon: 'ClipboardList',
    defaultW: 6, defaultH: 3,
    defaultProps: { showPriority: true, allowBulkActions: false },
    requiredCapabilities: ['approvals'],
    frontend: 'copilotkit',
  },
  // ─── Deep Agent-specific blocks ───
  {
    type: 'reasoningChain',
    label: 'Reasoning Chain',
    description: 'Visualize Deep Agent multi-step reasoning process',
    icon: 'Brain',
    defaultW: 6, defaultH: 4,
    defaultProps: { showConfidence: true, collapsible: true },
    requiredCapabilities: ['intermediateState', 'streaming'],
    frontend: 'copilotkit',
  },
  {
    type: 'subAgentTree',
    label: 'Sub-Agent Tree',
    description: 'Tree view of Deep Agent sub-agent hierarchy and delegation',
    icon: 'Network',
    defaultW: 6, defaultH: 4,
    defaultProps: { showStatus: true, animated: true },
    requiredCapabilities: ['subagents', 'progress'],
    frontend: 'copilotkit',
  },
  {
    type: 'depthIndicator',
    label: 'Depth Indicator',
    description: 'Shows current reasoning depth and progress for Deep Agent',
    icon: 'Gauge',
    defaultW: 3, defaultH: 1,
    defaultProps: { maxDepth: 5, showLabel: true },
    requiredCapabilities: ['progress'],
    frontend: 'copilotkit',
  },
];

export function getBlockDefinition(type: string): BlockDefinition | undefined {
  return BLOCK_REGISTRY.find((b) => b.type === type);
}
